repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
        files: \.(js|json|rb|md|py|sh|txt|yaml|yml)$
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-json
    -   id: end-of-file-fixer
-   repo: https://github.com/adrienverge/yamllint.git
    rev: v1.14.0
    hooks:
    -   id: yamllint
-   repo: https://github.com/jumanjihouse/pre-commit-hooks.git
    rev: 1.10.3
    hooks:
    -   id: rubocop
-   repo: https://github.com/willthames/ansible-lint.git
    rev: v4.0.1
    hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$
#-   repo: local
#    hooks:
#    -   id: travis-lint
#        name: Travis Lint
#        entry: bundle
#        language: system
#        files: ^\.travis\.yml$
#        args:
#        - exec
#       - travis
#        - lint
#        - --no-interactive
#        - --skip-version-check
#        - --skip-completion-check
#        - --exit-code
